### ISSUE TITLE
Slow automatic scrolling

### ISSUE THREAD

**Issue by rokf** [leafo/lapis-site#10]
When I visit http://leafo.net/lapis/ and scroll down below the **What is it?** section the site automatically very slowly scrolls up.

When the hello world example containers have enough margin at the top the scrolling stops.

My browser is **Firefox Quantum** 68.0.2 (64-bit), OS is Alpine Linux 3.10.2.

**Comment by leafo** [comment]
whoa, that's really strange. That site is much older than the most recent version of firefox, so.... 

I think it's related to some JS code I'm using to stick those headers. `position: sticky` is a thing now so I'll convert to that.
